sudo: required
dist: trusty
language: python
cache:
  directories:
    - "$HOME/.pip-cache/"
    - ".tox"
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8
install:
  - pip install --upgrade pip
  - pip install tox-travis
script: tox
